# Generated by Django 4.2 on 2025-05-05 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxdeclaration',
            options={'verbose_name': 'Mokėsčiai', 'verbose_name_plural': 'Mokėsčiai'},
        ),
    ]
